### ISSUE TITLE
bitbagcms compatibility

### ISSUE THREAD

**Issue by t-n-y** [netgen-layouts/layouts-sylius-bitbag#7]
Hi,

I wanted to know if you planned a compatibility with bitbagcms V4.
I was updating my project to sylius 1.12, and only the V4 of bitbagcms is compatible.  

Hope to read you soon

**Comment by emodric** [comment]
@t-n-y Hi!

This all depends on how complicated is the upgrade. I can't find any upgrade instructions at https://github.com/BitBagCommerce/SyliusCmsPlugin.

Currently, our time is a bit short due to project obligations, but I would be more than happy to accept a PR :)

**Comment by emodric** [comment]
Released with version 1.4.6.
